### PR TITLE
Zephyr Module and Update

### PR DESCRIPTION
**Pull request by XenuIsWatching**
tflite-lite has moved forward a couple of years since then. This pulls in the latest from the upstream and also creates the cmake as a zephyr module

My concern is about how the branch struction is gonna work here. tflite-micro has move forward quite a bit in a few years. the `zephyr` branch also had some cherry-picked patches from the upstream that are now on the `main` branch. When I started, I created a `zephyr2` branch to give me something to clean to work on and add my commits on top of them (some of them are the same as the existing `zephyr` branch which add `third-party-static` to the repo)

### CODE REVIEW

**Comment by stephanosio** [comment]
@laurenmurphyx64 Could you take a look at this?

**Comment by XenuIsWatching** [comment]
> @laurenmurphyx64 Could you take a look at this?

I ping'ed @laurenmurphyx64 through a direct message on Discord as well. I got no response. She appears to MIA. I'm not sure how to proceeded from here now :man_shrugging:

**Comment by stephanosio** [comment]
@XenuIsWatching I have added @JordanYates, the CMSIS-NN integration maintainer, since he might be interested in this. Also I will eventually try to get to reviewing this alongside other related PRs so these can make into the 3.5.

**Comment by JordanYates** [comment]
> My concern is about how the branch struction is gonna work here. tflite-micro has move forward quite a bit in a few years. the `zephyr` branch also had some cherry-picked patches from the upstream that are now on the `main` branch. When I started, I created a `zephyr2` branch to give me something to clean to work on and add my commits on top of them (some of them are the same as the existing `zephyr` branch which add `third-party-static` to the repo)

How branches are handled in modules is left up to the module maintainers. We had a similar problem with another module I work with (https://github.com/zephyrproject-rtos/loramac-node) and our decision was to make a new branch based off the upstream each time we moved to a new version. Sadly it doesn't look like `tflite-micro` does releases, but you could do something similar with the commit hash I guess.

**Comment by XenuIsWatching** [comment]
> > My concern is about how the branch struction is gonna work here. tflite-micro has move forward quite a bit in a few years. the `zephyr` branch also had some cherry-picked patches from the upstream that are now on the `main` branch. When I started, I created a `zephyr2` branch to give me something to clean to work on and add my commits on top of them (some of them are the same as the existing `zephyr` branch which add `third-party-static` to the repo)
> 
> How branches are handled in modules is left up to the module maintainers. We had a similar problem with another module I work with (https://github.com/zephyrproject-rtos/loramac-node) and our decision was to make a new branch based off the upstream each time we moved to a new version. Sadly it doesn't look like `tflite-micro` does releases, but you could do something similar with the commit hash I guess.

Yeah, that seems likely what we'll have to do, but right now the main issue seems to be tracking down @laurenmurphyx64

**Comment by XenuIsWatching** [comment]
rebasing on top of the upstream/main

**Comment by cfriedt** [comment]
I'm not sure how to get in touch with @laurenmurphyx64 (maybe Discord?).

If the API is not backward-compatible, then the old version might need to be deprecated and the newer version would then be built separately via Kconfig.

**Comment by XenuIsWatching** [comment]
> I'm not sure how to get in touch with @laurenmurphyx64 (maybe Discord?).

I try that already
 
> If the API is not backward-compatible, then the old version might need to be deprecated and the newer version would then be built separately via Kconfig.

I don't think that's necessary. I've got the samples updated to work with the new version.

**Comment by cfriedt** [comment]
This change seems to be very large - is that intentional?

**Comment by XenuIsWatching** [comment]
> This change seems to be very large - is that intentional?

yes, this is pulling from the upstream/main which hasn't been updated for a couple of years now

**Comment by cfriedt** [comment]
@XenuIsWatching - ah makes complete sense now. I just saw this was the module repo.

Do you have a separate issue in the main Zephyr repo? If so, please add the `TSC` label.

It could be the case that @laurenmurphyx64 is on leave or something. Normally, 2mo would be very long for a maintainer to not respond.

**Comment by Yaxit** [comment]
Hey, what's the blocking step to merge this?

Also @XenuIsWatching can we use your zephyr2 branch as an external west module in the meantime?

**Comment by Yaxit** [comment]
Is there a new version of `CMakeLists.txt` and `Kconfig` for the Zephyr module to build this?

**Comment by jahedul-haque** [comment]
Please provide the CMakrLists.txt and Kconfig to use the latest tflite micro repi

**Pull request merged**
